# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lT4VhNyXQLAer7uzuRUHDkB3jYN-KS7
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/content/data/cleaned_data.csv")

print(f"Loaded data: {df.shape}")

print(f"First 5 rows: \n{df.head(5)}")

df.shape

print("Average score :", df["score"].mean())

print("Average comments:", df["num_comments"].mean())

print("--- Numpy Stas ---")

print("Mean score:", np.mean(df["score"]))

print("Median score:", np.median(df["score"]))

print("Std deviation:", np.std(df["score"]))

print("Max score:", np.max(df["score"]))

print("Min score:", np.min(df["score"]))

print("Highest score:", df["score"].max())
print("Lowest score:", df["score"].min())

print("Most stories in:",df["category"].value_counts().idxmax())

most_commented = df.loc[df["num_comments"].idxmax()]
print("Most commented story:", most_commented["title"])
print("Comment count:", most_commented["num_comments"])

df["engagement"] = df["num_comments"] / (df["score"] + 1)

average_score = df["score"].mean()

df["is_popular"] = df["score"] > average_score

df.to_csv("data/trends_analysed.csv", index=False)

print(f"Saved {len(df)} rows to data/trends_analysed.csv")