# -*- coding: utf-8 -*-
"""task1_data_collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lT4VhNyXQLAer7uzuRUHDkB3jYN-KS7
"""

import requests
import time
import json
import os
from datetime import datetime


# ---------------------------------------------------
# 1. API URL and headers
# ---------------------------------------------------

top_stories_url = "https://hacker-news.firebaseio.com/v0/topstories.json"

headers = {
    "User-Agent": "TrendPulse/1.0"
}


# ---------------------------------------------------
# 2. Categories and their keywords
# ---------------------------------------------------

categories = {
    "technology": [
        "ai", "software", "tech", "code", "computer",
        "data", "cloud", "api", "gpu", "llm"
    ],

    "worldnews": [
        "war", "government", "country", "president",
        "election", "climate", "attack", "global"
    ],

    "sports": [
        "nfl", "nba", "fifa", "sport", "game",
        "team", "player", "league", "championship"
    ],

    "science": [
        "research", "study", "space", "physics",
        "biology", "discovery", "nasa", "genome"
    ],

    "entertainment": [
        "movie", "film", "music", "netflix",
        "game", "book", "show", "award", "streaming"
    ]
}


# ---------------------------------------------------
# 3. Fetch the top 500 story IDs
# ---------------------------------------------------

try:

    response = requests.get(
        top_stories_url,
        headers=headers,
        timeout=10
    )

    response.raise_for_status()

    story_ids = response.json()

    # We only need the first 500 stories
    story_ids = story_ids[:500]

    print("Successfully fetched", len(story_ids), "story IDs.")

except requests.RequestException as error:

    print("Failed to fetch top stories:", error)

    story_ids = []


# ---------------------------------------------------
# 4. Store all collected stories
# ---------------------------------------------------

all_stories = []


# ---------------------------------------------------
# 5. Keep track of stories already collected
# ---------------------------------------------------

used_ids = set()


# ---------------------------------------------------
# 6. Process each category
# ---------------------------------------------------

for category, keywords in categories.items():

    print("Processing category:", category)

    category_count = 0

    # Check the first 500 story IDs
    for story_id in story_ids:

        # Stop once we have 25 stories
        # for the current category
        if category_count >= 25:
            break

        # Create URL for individual story
        story_url = (
            f"https://hacker-news.firebaseio.com/v0/item/"
            f"{story_id}.json"
        )

        try:

            # Fetch story details
            response = requests.get(
                story_url,
                headers=headers,
                timeout=10
            )

            response.raise_for_status()

            story = response.json()

        except requests.RequestException as error:

            print(
                f"Failed to fetch story {story_id}:",
                error
            )

            # If this story fails, move to next story
            continue


        # ---------------------------------------------------
        # 7. Get the title from the story
        # ---------------------------------------------------

        title = story.get("title", "")

        # Convert title to lowercase
        # so keyword matching is case-insensitive
        title_lower = title.lower()


        # ---------------------------------------------------
        # 8. Check whether the title contains
        #    any keyword for the current category
        # ---------------------------------------------------

        if any(keyword in title_lower for keyword in keywords):

            # Avoid collecting the same story twice
            if story_id in used_ids:
                continue


            # ---------------------------------------------------
            # 9. Extract the required fields
            # ---------------------------------------------------

            record = {
                "post_id": story.get("id"),
                "title": title,
                "category": category,
                "score": story.get("score", 0),
                "num_comments": story.get("descendants", 0),
                "author": story.get("by", "unknown"),
                "collected_at": datetime.now().isoformat()
            }


            # Add the record to our main list
            all_stories.append(record)

            # Remember this story ID
            used_ids.add(story_id)

            # Increase category count
            category_count += 1

            print(
                f"  Collected {category_count}/25:",
                title
            )


    # ---------------------------------------------------
    # 10. Wait 2 seconds after each category
    # ---------------------------------------------------

    time.sleep(2)


# ---------------------------------------------------
# 11. Create the data folder
# ---------------------------------------------------

os.makedirs("data", exist_ok=True)


# ---------------------------------------------------
# 12. Create today's filename
# ---------------------------------------------------

date_string = datetime.now().strftime("%Y%m%d")

filename = f"data/trends_{date_string}.json"


# ---------------------------------------------------
# 13. Save all stories to JSON
# ---------------------------------------------------

with open(filename, "w", encoding="utf-8") as file:

    json.dump(
        all_stories,
        file,
        indent=4,
        ensure_ascii=False
    )


# ---------------------------------------------------
# 14. Print final result
# ---------------------------------------------------

print()
print(
    f"Collected {len(all_stories)} stories. "
    f"Saved to {filename}"
)