# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lT4VhNyXQLAer7uzuRUHDkB3jYN-KS7
"""

import pandas as pd

df=pd.read_json("/content/trends_20260901.json")

df

print(f"Loaded {len(df)} stories")

df=df.drop_duplicates(subset="post_id")

print("After removing duplicates:", len(df))

df=df.dropna(subset=["post_id","title","score"])

print("After removing missimg values:", len(df))

df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].fillna(0).astype(int)#same stories have might not comments.

df = df[df["score"] >= 5]
print("After removing low scores:", len(df))

df["title"] = df["title"].str.strip()

df.to_csv("data/trends_clean.csv", index=False)

import os
os.makedirs("data",exist_ok=True)
df.to_csv("data/cleaned_data.csv", index=False)

print(f"Saved {len(df)} rows to data/trends_clean.csv")

category_counts = df["category"].value_counts()

print("\nStories per category:")

for category, count in category_counts.items():
    print(f"  {category:<15} {count}")