# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lT4VhNyXQLAer7uzuRUHDkB3jYN-KS7
"""

import pandas as pd;import matplotlib.pyplot as plt;import os

df=pd.read_csv("/content/cleaned_data (1).csv")
df.columns

os.makedirs("outputs", exist_ok=True)

top10 = df.nlargest(10, "score")

top10["short_title"] = top10["title"].apply(
    lambda x: x[:50] + "..." if len(x) > 50 else x
)

plt.barh(top10["short_title"], top10["score"])

plt.xlabel("Score")
plt.ylabel("Story Title")
plt.title("Top 10 Stories by Score")

plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("outputs/chart1_top_stories.png")
plt.show()
plt.close()

category_counts = df["category"].value_counts()

colors = [
    "red",
    "blue",
    "green",
    "orange",
    "purple"
]

plt.figure(figsize=(8, 6))

plt.bar(
    category_counts.index,
    category_counts.values,
    color=colors[:len(category_counts)]
)

plt.xlabel("Category")
plt.ylabel("Number of Stories")
plt.title("Stories per Category")

plt.tight_layout()


plt.savefig("outputs/chart2_categories.png")

plt.show()

plt.close()
popular = df[df["is_popular"] == True]

not_popular = df[df["is_popular"] == False]

plt.figure(figsize=(8, 6))

plt.scatter(
    popular["score"],
    popular["num_comments"],
    label="Popular"
)

plt.scatter(
    not_popular["score"],
    not_popular["num_comments"],
    label="Not Popular"
)

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")

plt.legend()

plt.tight_layout()


plt.savefig("outputs/chart3_scatter.png")

plt.show()

plt.close()




fig, axes = plt.subplots(
    2,
    2,
    figsize=(15, 10)
)

fig.suptitle(
    "TrendPulse Dashboard",
    fontsize=18
)



axes[0, 0].barh(
    top10["short_title"],
    top10["score"]
)

axes[0, 0].set_title("Top 10 Stories by Score")
axes[0, 0].set_xlabel("Score")
axes[0, 0].set_ylabel("Story Title")

axes[0, 0].invert_yaxis()




axes[0, 1].bar(
    category_counts.index,
    category_counts.values,
    color=colors[:len(category_counts)]
)

axes[0, 1].set_title("Stories per Category")
axes[0, 1].set_xlabel("Category")
axes[0, 1].set_ylabel("Number of Stories")




axes[1, 0].scatter(
    popular["score"],
    popular["num_comments"],
    label="Popular"
)

axes[1, 0].scatter(
    not_popular["score"],
    not_popular["num_comments"],
    label="Not Popular"
)

axes[1, 0].set_title("Score vs Comments")
axes[1, 0].set_xlabel("Score")
axes[1, 0].set_ylabel("Number of Comments")

axes[1, 0].legend()



axes[1, 1].axis("off")



plt.tight_layout()


plt.savefig("outputs/dashboard.png")

plt.show()

plt.close()


print("All charts saved successfully!")